# Generated by Django 5.2.5 on 2025-08-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=150)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_material', models.CharField(blank=True, max_length=50, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grosor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'materiales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('total_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'ordenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenProductos',
            fields=[
                ('id_orden_producto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'orden_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParrillaMateriales',
            fields=[
                ('id_parrilla_material', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'parrilla_materiales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parrillas',
            fields=[
                ('id_parrilla', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('tolerancias', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'parrillas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('subtipo', models.CharField(blank=True, max_length=50, null=True)),
                ('acomodo', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('largo_gral', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho_gral', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grosor_gral', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('img_plano', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoServicios',
            fields=[
                ('id_producto_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'producto_servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
    ]
