# Generated by Django 5.2.5 on 2025-08-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grosor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tolerancia', models.CharField(blank=True, max_length=100, null=True)),
                ('separacion_TS', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_B', models.CharField(blank=True, max_length=50, null=True)),
                ('distancia_B', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'componentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id_costo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_madera', models.CharField(blank=True, max_length=50, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'costos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Materiales',
        ),
        migrations.DeleteModel(
            name='ParrillaMateriales',
        ),
        migrations.DeleteModel(
            name='Parrillas',
        ),
    ]
